"""Add models for techicical and added a ned columns , hourly rate

Revision ID: bbef6053608d
Revises: aadfc2514071
Create Date: 2025-07-06 17:44:21.553447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbef6053608d'
down_revision = 'aadfc2514071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_column('hourly_rate')

    # ### end Alembic commands ###
